default_chain: stride-testnet
chains:
  gaia-testnet:
    key: PortakalNode
    chain-id: GAIA
    rpc-addr: http://62.171.166.5:23657      # Gaia RPC yazacağız
    grpc-addr: http://62.171.166.5:23090     # Gaia GRPC yazacağız
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001uatom
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  stride-testnet:
    key: PortakalNode
    chain-id: STRIDE-TESTNET-4
    rpc-addr: http://127.0.0.1:26657      # Stride RPC yazacağız
    grpc-addr: http://62.171.166.5:9090     # Stride GRPC yazacağıze
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001ustrd
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
